/*
 *
 *  NTC.swift Name That Color (Swift)
 *  Created by Thomas Hazlett on 17/05/2017.
 *
 *
 *  Based off Chirag Mehta's ntc.js - http://chir.ag/projects/ntc
 *
 *
 *  Usage: NTC.nameOf(UIColor(red: 0.4, green: 0.8, blue: 0.5, alpha: 1.0))
 *
 */

import UIKit

class NTC {
    
    public class func nameOf(_ color : UIColor) -> String{
        var r : CGFloat = 0.0
        var g : CGFloat = 0.0
        var b : CGFloat = 0.0
        var a : CGFloat = 0.0
        
        color.getRed(&r, green: &g, blue: &b, alpha: &a)
        
        let ri : Int = Int(round(r * 255.0))
        let gi : Int = Int(round(g * 255.0))
        let bi : Int = Int(round(b * 255.0))
        
        var rs = String(ri, radix: 16)
        var gs = String(gi, radix: 16)
        var bs = String(bi, radix: 16)
        
        if(rs.characters.count == 1) { rs = "0" + rs }
        if(gs.characters.count == 1) { gs = "0" + gs }
        if(bs.characters.count == 1) { bs = "0" + bs }
        
        let colorString = rs+gs+bs
        
        
        return NTC.name(colorString)
    }
    
    
    private class func rgb(color : String) -> [Int] {
        
        let rs = color.index(color.startIndex, offsetBy: 1)
        let re = color.index(color.startIndex, offsetBy: 3)
        let red = rs..<re
        
        let gs = color.index(color.startIndex, offsetBy: 3)
        let ge = color.index(color.startIndex, offsetBy: 5)
        let green = gs..<ge
        
        let bs = color.index(color.startIndex, offsetBy: 5)
        let be = color.index(color.startIndex, offsetBy: 7)
        let blue = bs..<be
        
        
        return [Int(color.substring(with: red), radix: 16)!, Int(color.substring(with: green), radix: 16)!, Int(color.substring(with: blue), radix: 16)!]
        
    }
    
    private class func hsl(color : String) -> [Int] {
        
        let rs = color.index(color.startIndex, offsetBy: 1)
        let re = color.index(color.startIndex, offsetBy: 3)
        let red = rs..<re
        
        let gs = color.index(color.startIndex, offsetBy: 3)
        let ge = color.index(color.startIndex, offsetBy: 5)
        let green = gs..<ge
        
        let bs = color.index(color.startIndex, offsetBy: 5)
        let be = color.index(color.startIndex, offsetBy: 7)
        let blue = bs..<be
        
        let rgb = [CGFloat(Int(color.substring(with: red), radix: 16)!) / 255.0, CGFloat(Int(color.substring(with: green), radix: 16)!) / 255.0, CGFloat(Int(color.substring(with: blue), radix: 16)!) / 255.0]
        
        let r = rgb[0]
        let g = rgb[1]
        let b = rgb[2]
        
        let mn = min(r, min(g,b))
        let mx = max(r, max(g,b))
        let dlt = mx - mn
        let l = (mn + mx) / 2.0
        
        var s : CGFloat = 0.0
        if ( l > 0.0 && l < 1.0) {
            s = dlt / (l < 0.5 ? (l * 2.0) : (2.0 - 2.0*l))
        }
        
        var h : CGFloat = 0.0
        if (dlt > 0) {
            if (mx == r && mx != g) { h += (g - b) / dlt }
            if (mx == g && mx != b) { h += (2 + (b - r) / dlt) }
            if (mx == b && mx != r) { h += (4 + (r - g) / dlt) }
            h /= 6
        }
        
        return [Int(h * 255), Int(s * 255), Int(l * 255)]
        
    }
    
    
    private class func name(_ col : String) -> String {
        
        var color = col
        
        if( color.characters.count % 3 == 0) { color = "#" + color }
        
        let rgbv = rgb(color: color)
        let r = rgbv[0]
        let g = rgbv[1]
        let b = rgbv[2]
        
        let hslv = hsl(color: color)
        let h = hslv[0]
        let s = hslv[1]
        let l = hslv[2]
        
        var ndf1 = 0
        var ndf2 = 0
        var ndf = 0
        
        var cl = -1
        var df = -1
        
        var cnt = 0
        for i : [String] in NTC.names {
            if(color == "#" + i[0]) {
                return i[1]
            }
            
            ndf1 = (r - Int(i[2])!)*(r - Int(i[2])!)
            ndf1 += (g - Int(i[3])!)*(g - Int(i[3])!)
            ndf1 += (b - Int(i[4])!)*(b - Int(i[4])!)
            
            ndf2 = (h - Int(i[5])!)*(h - Int(i[5])!)
            ndf2 += (s - Int(i[6])!)*(s - Int(i[6])!)
            ndf2 += (l - Int(i[7])!)*(l - Int(i[7])!)
            ndf = ndf1 + ndf2 * 2
            
            if( df < 0 || df > ndf ) {
                df = ndf
                cl = cnt
            }
            
            cnt+=1
            
        }
        
        
        return cl < 0 ? "Invalid Color" : NTC.names[cl][1]
        
    }
    
    

    private static var _names = [[String]]()
    private class var names : [[String]] {
        get {
            if(_names.count == 0) {
                _names.append(["000000", "Black"])
                _names.append(["000080", "Navy Blue"])
                _names.append(["0000C8", "Dark Blue"])
                _names.append(["0000FF", "Blue"])
                _names.append(["000741", "Stratos"])
                _names.append(["001B1C", "Swamp"])
                _names.append(["002387", "Resolution Blue"])
                _names.append(["002900", "Deep Fir"])
                _names.append(["002E20", "Burnham"])
                _names.append(["002FA7", "International Klein Blue"])
                _names.append(["003153", "Prussian Blue"])
                _names.append(["003366", "Midnight Blue"])
                _names.append(["003399", "Smalt"])
                _names.append(["003532", "Deep Teal"])
                _names.append(["003E40", "Cyprus"])
                _names.append(["004620", "Kaitoke Green"])
                _names.append(["0047AB", "Cobalt"])
                _names.append(["004816", "Crusoe"])
                _names.append(["004950", "Sherpa Blue"])
                _names.append(["0056A7", "Endeavour"])
                _names.append(["00581A", "Camarone"])
                _names.append(["0066CC", "Science Blue"])
                _names.append(["0066FF", "Blue Ribbon"])
                _names.append(["00755E", "Tropical Rain Forest"])
                _names.append(["0076A3", "Allports"])
                _names.append(["007BA7", "Deep Cerulean"])
                _names.append(["007EC7", "Lochmara"])
                _names.append(["007FFF", "Azure Radiance"])
                _names.append(["008080", "Teal"])
                _names.append(["0095B6", "Bondi Blue"])
                _names.append(["009DC4", "Pacific Blue"])
                _names.append(["00A693", "Persian Green"])
                _names.append(["00A86B", "Jade"])
                _names.append(["00CC99", "Caribbean Green"])
                _names.append(["00CCCC", "Robin's Egg Blue"])
                _names.append(["00FF00", "Green"])
                _names.append(["00FF7F", "Spring Green"])
                _names.append(["00FFFF", "Cyan / Aqua"])
                _names.append(["010D1A", "Blue Charcoal"])
                _names.append(["011635", "Midnight"])
                _names.append(["011D13", "Holly"])
                _names.append(["012731", "Daintree"])
                _names.append(["01361C", "Cardin Green"])
                _names.append(["01371A", "County Green"])
                _names.append(["013E62", "Astronaut Blue"])
                _names.append(["013F6A", "Regal Blue"])
                _names.append(["014B43", "Aqua Deep"])
                _names.append(["015E85", "Orient"])
                _names.append(["016162", "Blue Stone"])
                _names.append(["016D39", "Fun Green"])
                _names.append(["01796F", "Pine Green"])
                _names.append(["017987", "Blue Lagoon"])
                _names.append(["01826B", "Deep Sea"])
                _names.append(["01A368", "Green Haze"])
                _names.append(["022D15", "English Holly"])
                _names.append(["02402C", "Sherwood Green"])
                _names.append(["02478E", "Congress Blue"])
                _names.append(["024E46", "Evening Sea"])
                _names.append(["026395", "Bahama Blue"])
                _names.append(["02866F", "Observatory"])
                _names.append(["02A4D3", "Cerulean"])
                _names.append(["03163C", "Tangaroa"])
                _names.append(["032B52", "Green Vogue"])
                _names.append(["036A6E", "Mosque"])
                _names.append(["041004", "Midnight Moss"])
                _names.append(["041322", "Black Pearl"])
                _names.append(["042E4C", "Blue Whale"])
                _names.append(["044022", "Zuccini"])
                _names.append(["044259", "Teal Blue"])
                _names.append(["051040", "Deep Cove"])
                _names.append(["051657", "Gulf Blue"])
                _names.append(["055989", "Venice Blue"])
                _names.append(["056F57", "Watercourse"])
                _names.append(["062A78", "Catalina Blue"])
                _names.append(["063537", "Tiber"])
                _names.append(["069B81", "Gossamer"])
                _names.append(["06A189", "Niagara"])
                _names.append(["073A50", "Tarawera"])
                _names.append(["080110", "Jaguar"])
                _names.append(["081910", "Black Bean"])
                _names.append(["082567", "Deep Sapphire"])
                _names.append(["088370", "Elf Green"])
                _names.append(["08E8DE", "Bright Turquoise"])
                _names.append(["092256", "Downriver"])
                _names.append(["09230F", "Palm Green"])
                _names.append(["09255D", "Madison"])
                _names.append(["093624", "Bottle Green"])
                _names.append(["095859", "Deep Sea Green"])
                _names.append(["097F4B", "Salem"])
                _names.append(["0A001C", "Black Russian"])
                _names.append(["0A480D", "Dark Fern"])
                _names.append(["0A6906", "Japanese Laurel"])
                _names.append(["0A6F75", "Atoll"])
                _names.append(["0B0B0B", "Cod Gray"])
                _names.append(["0B0F08", "Marshland"])
                _names.append(["0B1107", "Gordons Green"])
                _names.append(["0B1304", "Black Forest"])
                _names.append(["0B6207", "San Felix"])
                _names.append(["0BDA51", "Malachite"])
                _names.append(["0C0B1D", "Ebony"])
                _names.append(["0C0D0F", "Woodsmoke"])
                _names.append(["0C1911", "Racing Green"])
                _names.append(["0C7A79", "Surfie Green"])
                _names.append(["0C8990", "Blue Chill"])
                _names.append(["0D0332", "Black Rock"])
                _names.append(["0D1117", "Bunker"])
                _names.append(["0D1C19", "Aztec"])
                _names.append(["0D2E1C", "Bush"])
                _names.append(["0E0E18", "Cinder"])
                _names.append(["0E2A30", "Firefly"])
                _names.append(["0F2D9E", "Torea Bay"])
                _names.append(["10121D", "Vulcan"])
                _names.append(["101405", "Green Waterloo"])
                _names.append(["105852", "Eden"])
                _names.append(["110C6C", "Arapawa"])
                _names.append(["120A8F", "Ultramarine"])
                _names.append(["123447", "Elephant"])
                _names.append(["126B40", "Jewel"])
                _names.append(["130000", "Diesel"])
                _names.append(["130A06", "Asphalt"])
                _names.append(["13264D", "Blue Zodiac"])
                _names.append(["134F19", "Parsley"])
                _names.append(["140600", "Nero"])
                _names.append(["1450AA", "Tory Blue"])
                _names.append(["151F4C", "Bunting"])
                _names.append(["1560BD", "Denim"])
                _names.append(["15736B", "Genoa"])
                _names.append(["161928", "Mirage"])
                _names.append(["161D10", "Hunter Green"])
                _names.append(["162A40", "Big Stone"])
                _names.append(["163222", "Celtic"])
                _names.append(["16322C", "Timber Green"])
                _names.append(["163531", "Gable Green"])
                _names.append(["171F04", "Pine Tree"])
                _names.append(["175579", "Chathams Blue"])
                _names.append(["182D09", "Deep Forest Green"])
                _names.append(["18587A", "Blumine"])
                _names.append(["19330E", "Palm Leaf"])
                _names.append(["193751", "Nile Blue"])
                _names.append(["1959A8", "Fun Blue"])
                _names.append(["1A1A68", "Lucky Point"])
                _names.append(["1AB385", "Mountain Meadow"])
                _names.append(["1B0245", "Tolopea"])
                _names.append(["1B1035", "Haiti"])
                _names.append(["1B127B", "Deep Koamaru"])
                _names.append(["1B1404", "Acadia"])
                _names.append(["1B2F11", "Seaweed"])
                _names.append(["1B3162", "Biscay"])
                _names.append(["1B659D", "Matisse"])
                _names.append(["1C1208", "Crowshead"])
                _names.append(["1C1E13", "Rangoon Green"])
                _names.append(["1C39BB", "Persian Blue"])
                _names.append(["1C402E", "Everglade"])
                _names.append(["1C7C7D", "Elm"])
                _names.append(["1D6142", "Green Pea"])
                _names.append(["1E0F04", "Creole"])
                _names.append(["1E1609", "Karaka"])
                _names.append(["1E1708", "El Paso"])
                _names.append(["1E385B", "Cello"])
                _names.append(["1E433C", "Te Papa Green"])
                _names.append(["1E90FF", "Dodger Blue"])
                _names.append(["1E9AB0", "Eastern Blue"])
                _names.append(["1F120F", "Night Rider"])
                _names.append(["1FC2C2", "Java"])
                _names.append(["20208D", "Jacksons Purple"])
                _names.append(["202E54", "Cloud Burst"])
                _names.append(["204852", "Blue Dianne"])
                _names.append(["211A0E", "Eternity"])
                _names.append(["220878", "Deep Blue"])
                _names.append(["228B22", "Forest Green"])
                _names.append(["233418", "Mallard"])
                _names.append(["240A40", "Violet"])
                _names.append(["240C02", "Kilamanjaro"])
                _names.append(["242A1D", "Log Cabin"])
                _names.append(["242E16", "Black Olive"])
                _names.append(["24500F", "Green House"])
                _names.append(["251607", "Graphite"])
                _names.append(["251706", "Cannon Black"])
                _names.append(["251F4F", "Port Gore"])
                _names.append(["25272C", "Shark"])
                _names.append(["25311C", "Green Kelp"])
                _names.append(["2596D1", "Curious Blue"])
                _names.append(["260368", "Paua"])
                _names.append(["26056A", "Paris M"])
                _names.append(["261105", "Wood Bark"])
                _names.append(["261414", "Gondola"])
                _names.append(["262335", "Steel Gray"])
                _names.append(["26283B", "Ebony Clay"])
                _names.append(["273A81", "Bay of Many"])
                _names.append(["27504B", "Plantation"])
                _names.append(["278A5B", "Eucalyptus"])
                _names.append(["281E15", "Oil"])
                _names.append(["283A77", "Astronaut"])
                _names.append(["286ACD", "Mariner"])
                _names.append(["290C5E", "Violent Violet"])
                _names.append(["292130", "Bastille"])
                _names.append(["292319", "Zeus"])
                _names.append(["292937", "Charade"])
                _names.append(["297B9A", "Jelly Bean"])
                _names.append(["29AB87", "Jungle Green"])
                _names.append(["2A0359", "Cherry Pie"])
                _names.append(["2A140E", "Coffee Bean"])
                _names.append(["2A2630", "Baltic Sea"])
                _names.append(["2A380B", "Turtle Green"])
                _names.append(["2A52BE", "Cerulean Blue"])
                _names.append(["2B0202", "Sepia Black"])
                _names.append(["2B194F", "Valhalla"])
                _names.append(["2B3228", "Heavy Metal"])
                _names.append(["2C0E8C", "Blue Gem"])
                _names.append(["2C1632", "Revolver"])
                _names.append(["2C2133", "Bleached Cedar"])
                _names.append(["2C8C84", "Lochinvar"])
                _names.append(["2D2510", "Mikado"])
                _names.append(["2D383A", "Outer Space"])
                _names.append(["2D569B", "St Tropaz"])
                _names.append(["2E0329", "Jacaranda"])
                _names.append(["2E1905", "Jacko Bean"])
                _names.append(["2E3222", "Rangitoto"])
                _names.append(["2E3F62", "Rhino"])
                _names.append(["2E8B57", "Sea Green"])
                _names.append(["2EBFD4", "Scooter"])
                _names.append(["2F270E", "Onion"])
                _names.append(["2F3CB3", "Governor Bay"])
                _names.append(["2F519E", "Sapphire"])
                _names.append(["2F5A57", "Spectra"])
                _names.append(["2F6168", "Casal"])
                _names.append(["300529", "Melanzane"])
                _names.append(["301F1E", "Cocoa Brown"])
                _names.append(["302A0F", "Woodrush"])
                _names.append(["304B6A", "San Juan"])
                _names.append(["30D5C8", "Turquoise"])
                _names.append(["311C17", "Eclipse"])
                _names.append(["314459", "Pickled Bluewood"])
                _names.append(["315BA1", "Azure"])
                _names.append(["31728D", "Calypso"])
                _names.append(["317D82", "Paradiso"])
                _names.append(["32127A", "Persian Indigo"])
                _names.append(["32293A", "Blackcurrant"])
                _names.append(["323232", "Mine Shaft"])
                _names.append(["325D52", "Stromboli"])
                _names.append(["327C14", "Bilbao"])
                _names.append(["327DA0", "Astral"])
                _names.append(["33036B", "Christalle"])
                _names.append(["33292F", "Thunder"])
                _names.append(["33CC99", "Shamrock"])
                _names.append(["341515", "Tamarind"])
                _names.append(["350036", "Mardi Gras"])
                _names.append(["350E42", "Valentino"])
                _names.append(["350E57", "Jagger"])
                _names.append(["353542", "Tuna"])
                _names.append(["354E8C", "Chambray"])
                _names.append(["363050", "Martinique"])
                _names.append(["363534", "Tuatara"])
                _names.append(["363C0D", "Waiouru"])
                _names.append(["36747D", "Ming"])
                _names.append(["368716", "La Palma"])
                _names.append(["370202", "Chocolate"])
                _names.append(["371D09", "Clinker"])
                _names.append(["37290E", "Brown Tumbleweed"])
                _names.append(["373021", "Birch"])
                _names.append(["377475", "Oracle"])
                _names.append(["380474", "Blue Diamond"])
                _names.append(["381A51", "Grape"])
                _names.append(["383533", "Dune"])
                _names.append(["384555", "Oxford Blue"])
                _names.append(["384910", "Clover"])
                _names.append(["394851", "Limed Spruce"])
                _names.append(["396413", "Dell"])
                _names.append(["3A0020", "Toledo"])
                _names.append(["3A2010", "Sambuca"])
                _names.append(["3A2A6A", "Jacarta"])
                _names.append(["3A686C", "William"])
                _names.append(["3A6A47", "Killarney"])
                _names.append(["3AB09E", "Keppel"])
                _names.append(["3B000B", "Temptress"])
                _names.append(["3B0910", "Aubergine"])
                _names.append(["3B1F1F", "Jon"])
                _names.append(["3B2820", "Treehouse"])
                _names.append(["3B7A57", "Amazon"])
                _names.append(["3B91B4", "Boston Blue"])
                _names.append(["3C0878", "Windsor"])
                _names.append(["3C1206", "Rebel"])
                _names.append(["3C1F76", "Meteorite"])
                _names.append(["3C2005", "Dark Ebony"])
                _names.append(["3C3910", "Camouflage"])
                _names.append(["3C4151", "Bright Gray"])
                _names.append(["3C4443", "Cape Cod"])
                _names.append(["3C493A", "Lunar Green"])
                _names.append(["3D0C02", "Bean  "])
                _names.append(["3D2B1F", "Bistre"])
                _names.append(["3D7D52", "Goblin"])
                _names.append(["3E0480", "Kingfisher Daisy"])
                _names.append(["3E1C14", "Cedar"])
                _names.append(["3E2B23", "English Walnut"])
                _names.append(["3E2C1C", "Black Marlin"])
                _names.append(["3E3A44", "Ship Gray"])
                _names.append(["3EABBF", "Pelorous"])
                _names.append(["3F2109", "Bronze"])
                _names.append(["3F2500", "Cola"])
                _names.append(["3F3002", "Madras"])
                _names.append(["3F307F", "Minsk"])
                _names.append(["3F4C3A", "Cabbage Pont"])
                _names.append(["3F583B", "Tom Thumb"])
                _names.append(["3F5D53", "Mineral Green"])
                _names.append(["3FC1AA", "Puerto Rico"])
                _names.append(["3FFF00", "Harlequin"])
                _names.append(["401801", "Brown Pod"])
                _names.append(["40291D", "Cork"])
                _names.append(["403B38", "Masala"])
                _names.append(["403D19", "Thatch Green"])
                _names.append(["405169", "Fiord"])
                _names.append(["40826D", "Viridian"])
                _names.append(["40A860", "Chateau Green"])
                _names.append(["410056", "Ripe Plum"])
                _names.append(["411F10", "Paco"])
                _names.append(["412010", "Deep Oak"])
                _names.append(["413C37", "Merlin"])
                _names.append(["414257", "Gun Powder"])
                _names.append(["414C7D", "East Bay"])
                _names.append(["4169E1", "Royal Blue"])
                _names.append(["41AA78", "Ocean Green"])
                _names.append(["420303", "Burnt Maroon"])
                _names.append(["423921", "Lisbon Brown"])
                _names.append(["427977", "Faded Jade"])
                _names.append(["431560", "Scarlet Gum"])
                _names.append(["433120", "Iroko"])
                _names.append(["433E37", "Armadillo"])
                _names.append(["434C59", "River Bed"])
                _names.append(["436A0D", "Green Leaf"])
                _names.append(["44012D", "Barossa"])
                _names.append(["441D00", "Morocco Brown"])
                _names.append(["444954", "Mako"])
                _names.append(["454936", "Kelp"])
                _names.append(["456CAC", "San Marino"])
                _names.append(["45B1E8", "Picton Blue"])
                _names.append(["460B41", "Loulou"])
                _names.append(["462425", "Crater Brown"])
                _names.append(["465945", "Gray Asparagus"])
                _names.append(["4682B4", "Steel Blue"])
                _names.append(["480404", "Rustic Red"])
                _names.append(["480607", "Bulgarian Rose"])
                _names.append(["480656", "Clairvoyant"])
                _names.append(["481C1C", "Cocoa Bean"])
                _names.append(["483131", "Woody Brown"])
                _names.append(["483C32", "Taupe"])
                _names.append(["49170C", "Van Cleef"])
                _names.append(["492615", "Brown Derby"])
                _names.append(["49371B", "Metallic Bronze"])
                _names.append(["495400", "Verdun Green"])
                _names.append(["496679", "Blue Bayoux"])
                _names.append(["497183", "Bismark"])
                _names.append(["4A2A04", "Bracken"])
                _names.append(["4A3004", "Deep Bronze"])
                _names.append(["4A3C30", "Mondo"])
                _names.append(["4A4244", "Tundora"])
                _names.append(["4A444B", "Gravel"])
                _names.append(["4A4E5A", "Trout"])
                _names.append(["4B0082", "Pigment Indigo"])
                _names.append(["4B5D52", "Nandor"])
                _names.append(["4C3024", "Saddle"])
                _names.append(["4C4F56", "Abbey"])
                _names.append(["4D0135", "Blackberry"])
                _names.append(["4D0A18", "Cab Sav"])
                _names.append(["4D1E01", "Indian Tan"])
                _names.append(["4D282D", "Cowboy"])
                _names.append(["4D282E", "Livid Brown"])
                _names.append(["4D3833", "Rock"])
                _names.append(["4D3D14", "Punga"])
                _names.append(["4D400F", "Bronzetone"])
                _names.append(["4D5328", "Woodland"])
                _names.append(["4E0606", "Mahogany"])
                _names.append(["4E2A5A", "Bossanova"])
                _names.append(["4E3B41", "Matterhorn"])
                _names.append(["4E420C", "Bronze Olive"])
                _names.append(["4E4562", "Mulled Wine"])
                _names.append(["4E6649", "Axolotl"])
                _names.append(["4E7F9E", "Wedgewood"])
                _names.append(["4EABD1", "Shakespeare"])
                _names.append(["4F1C70", "Honey Flower"])
                _names.append(["4F2398", "Daisy Bush"])
                _names.append(["4F69C6", "Indigo"])
                _names.append(["4F7942", "Fern Green"])
                _names.append(["4F9D5D", "Fruit Salad"])
                _names.append(["4FA83D", "Apple"])
                _names.append(["504351", "Mortar"])
                _names.append(["507096", "Kashmir Blue"])
                _names.append(["507672", "Cutty Sark"])
                _names.append(["50C878", "Emerald"])
                _names.append(["514649", "Emperor"])
                _names.append(["516E3D", "Chalet Green"])
                _names.append(["517C66", "Como"])
                _names.append(["51808F", "Smalt Blue"])
                _names.append(["52001F", "Castro"])
                _names.append(["520C17", "Maroon Oak"])
                _names.append(["523C94", "Gigas"])
                _names.append(["533455", "Voodoo"])
                _names.append(["534491", "Victoria"])
                _names.append(["53824B", "Hippie Green"])
                _names.append(["541012", "Heath"])
                _names.append(["544333", "Judge Gray"])
                _names.append(["54534D", "Fuscous Gray"])
                _names.append(["549019", "Vida Loca"])
                _names.append(["55280C", "Cioccolato"])
                _names.append(["555B10", "Saratoga"])
                _names.append(["556D56", "Finlandia"])
                _names.append(["5590D9", "Havelock Blue"])
                _names.append(["56B4BE", "Fountain Blue"])
                _names.append(["578363", "Spring Leaves"])
                _names.append(["583401", "Saddle Brown"])
                _names.append(["585562", "Scarpa Flow"])
                _names.append(["587156", "Cactus"])
                _names.append(["589AAF", "Hippie Blue"])
                _names.append(["591D35", "Wine Berry"])
                _names.append(["592804", "Brown Bramble"])
                _names.append(["593737", "Congo Brown"])
                _names.append(["594433", "Millbrook"])
                _names.append(["5A6E9C", "Waikawa Gray"])
                _names.append(["5A87A0", "Horizon"])
                _names.append(["5B3013", "Jambalaya"])
                _names.append(["5C0120", "Bordeaux"])
                _names.append(["5C0536", "Mulberry Wood"])
                _names.append(["5C2E01", "Carnaby Tan"])
                _names.append(["5C5D75", "Comet"])
                _names.append(["5D1E0F", "Redwood"])
                _names.append(["5D4C51", "Don Juan"])
                _names.append(["5D5C58", "Chicago"])
                _names.append(["5D5E37", "Verdigris"])
                _names.append(["5D7747", "Dingley"])
                _names.append(["5DA19F", "Breaker Bay"])
                _names.append(["5E483E", "Kabul"])
                _names.append(["5E5D3B", "Hemlock"])
                _names.append(["5F3D26", "Irish Coffee"])
                _names.append(["5F5F6E", "Mid Gray"])
                _names.append(["5F6672", "Shuttle Gray"])
                _names.append(["5FA777", "Aqua Forest"])
                _names.append(["5FB3AC", "Tradewind"])
                _names.append(["604913", "Horses Neck"])
                _names.append(["605B73", "Smoky"])
                _names.append(["606E68", "Corduroy"])
                _names.append(["6093D1", "Danube"])
                _names.append(["612718", "Espresso"])
                _names.append(["614051", "Eggplant"])
                _names.append(["615D30", "Costa Del Sol"])
                _names.append(["61845F", "Glade Green"])
                _names.append(["622F30", "Buccaneer"])
                _names.append(["623F2D", "Quincy"])
                _names.append(["624E9A", "Butterfly Bush"])
                _names.append(["625119", "West Coast"])
                _names.append(["626649", "Finch"])
                _names.append(["639A8F", "Patina"])
                _names.append(["63B76C", "Fern"])
                _names.append(["6456B7", "Blue Violet"])
                _names.append(["646077", "Dolphin"])
                _names.append(["646463", "Storm Dust"])
                _names.append(["646A54", "Siam"])
                _names.append(["646E75", "Nevada"])
                _names.append(["6495ED", "Cornflower Blue"])
                _names.append(["64CCDB", "Viking"])
                _names.append(["65000B", "Rosewood"])
                _names.append(["651A14", "Cherrywood"])
                _names.append(["652DC1", "Purple Heart"])
                _names.append(["657220", "Fern Frond"])
                _names.append(["65745D", "Willow Grove"])
                _names.append(["65869F", "Hoki"])
                _names.append(["660045", "Pompadour"])
                _names.append(["660099", "Purple"])
                _names.append(["66023C", "Tyrian Purple"])
                _names.append(["661010", "Dark Tan"])
                _names.append(["66B58F", "Silver Tree"])
                _names.append(["66FF00", "Bright Green"])
                _names.append(["66FF66", "Screamin' Green"])
                _names.append(["67032D", "Black Rose"])
                _names.append(["675FA6", "Scampi"])
                _names.append(["676662", "Ironside Gray"])
                _names.append(["678975", "Viridian Green"])
                _names.append(["67A712", "Christi"])
                _names.append(["683600", "Nutmeg Wood Finish"])
                _names.append(["685558", "Zambezi"])
                _names.append(["685E6E", "Salt Box"])
                _names.append(["692545", "Tawny Port"])
                _names.append(["692D54", "Finn"])
                _names.append(["695F62", "Scorpion"])
                _names.append(["697E9A", "Lynch"])
                _names.append(["6A442E", "Spice"])
                _names.append(["6A5D1B", "Himalaya"])
                _names.append(["6A6051", "Soya Bean"])
                _names.append(["6B2A14", "Hairy Heath"])
                _names.append(["6B3FA0", "Royal Purple"])
                _names.append(["6B4E31", "Shingle Fawn"])
                _names.append(["6B5755", "Dorado"])
                _names.append(["6B8BA2", "Bermuda Gray"])
                _names.append(["6B8E23", "Olive Drab"])
                _names.append(["6C3082", "Eminence"])
                _names.append(["6CDAE7", "Turquoise Blue"])
                _names.append(["6D0101", "Lonestar"])
                _names.append(["6D5E54", "Pine Cone"])
                _names.append(["6D6C6C", "Dove Gray"])
                _names.append(["6D9292", "Juniper"])
                _names.append(["6D92A1", "Gothic"])
                _names.append(["6E0902", "Red Oxide"])
                _names.append(["6E1D14", "Moccaccino"])
                _names.append(["6E4826", "Pickled Bean"])
                _names.append(["6E4B26", "Dallas"])
                _names.append(["6E6D57", "Kokoda"])
                _names.append(["6E7783", "Pale Sky"])
                _names.append(["6F440C", "Cafe Royale"])
                _names.append(["6F6A61", "Flint"])
                _names.append(["6F8E63", "Highland"])
                _names.append(["6F9D02", "Limeade"])
                _names.append(["6FD0C5", "Downy"])
                _names.append(["701C1C", "Persian Plum"])
                _names.append(["704214", "Sepia"])
                _names.append(["704A07", "Antique Bronze"])
                _names.append(["704F50", "Ferra"])
                _names.append(["706555", "Coffee"])
                _names.append(["708090", "Slate Gray"])
                _names.append(["711A00", "Cedar Wood Finish"])
                _names.append(["71291D", "Metallic Copper"])
                _names.append(["714693", "Affair"])
                _names.append(["714AB2", "Studio"])
                _names.append(["715D47", "Tobacco Brown"])
                _names.append(["716338", "Yellow Metal"])
                _names.append(["716B56", "Peat"])
                _names.append(["716E10", "Olivetone"])
                _names.append(["717486", "Storm Gray"])
                _names.append(["718080", "Sirocco"])
                _names.append(["71D9E2", "Aquamarine Blue"])
                _names.append(["72010F", "Venetian Red"])
                _names.append(["724A2F", "Old Copper"])
                _names.append(["726D4E", "Go Ben"])
                _names.append(["727B89", "Raven"])
                _names.append(["731E8F", "Seance"])
                _names.append(["734A12", "Raw Umber"])
                _names.append(["736C9F", "Kimberly"])
                _names.append(["736D58", "Crocodile"])
                _names.append(["737829", "Crete"])
                _names.append(["738678", "Xanadu"])
                _names.append(["74640D", "Spicy Mustard"])
                _names.append(["747D63", "Limed Ash"])
                _names.append(["747D83", "Rolling Stone"])
                _names.append(["748881", "Blue Smoke"])
                _names.append(["749378", "Laurel"])
                _names.append(["74C365", "Mantis"])
                _names.append(["755A57", "Russett"])
                _names.append(["7563A8", "Deluge"])
                _names.append(["76395D", "Cosmic"])
                _names.append(["7666C6", "Blue Marguerite"])
                _names.append(["76BD17", "Lima"])
                _names.append(["76D7EA", "Sky Blue"])
                _names.append(["770F05", "Dark Burgundy"])
                _names.append(["771F1F", "Crown of Thorns"])
                _names.append(["773F1A", "Walnut"])
                _names.append(["776F61", "Pablo"])
                _names.append(["778120", "Pacifika"])
                _names.append(["779E86", "Oxley"])
                _names.append(["77DD77", "Pastel Green"])
                _names.append(["780109", "Japanese Maple"])
                _names.append(["782D19", "Mocha"])
                _names.append(["782F16", "Peanut"])
                _names.append(["78866B", "Camouflage Green"])
                _names.append(["788A25", "Wasabi"])
                _names.append(["788BBA", "Ship Cove"])
                _names.append(["78A39C", "Sea Nymph"])
                _names.append(["795D4C", "Roman Coffee"])
                _names.append(["796878", "Old Lavender"])
                _names.append(["796989", "Rum"])
                _names.append(["796A78", "Fedora"])
                _names.append(["796D62", "Sandstone"])
                _names.append(["79DEEC", "Spray"])
                _names.append(["7A013A", "Siren"])
                _names.append(["7A58C1", "Fuchsia Blue"])
                _names.append(["7A7A7A", "Boulder"])
                _names.append(["7A89B8", "Wild Blue Yonder"])
                _names.append(["7AC488", "De York"])
                _names.append(["7B3801", "Red Beech"])
                _names.append(["7B3F00", "Cinnamon"])
                _names.append(["7B6608", "Yukon Gold"])
                _names.append(["7B7874", "Tapa"])
                _names.append(["7B7C94", "Waterloo "])
                _names.append(["7B8265", "Flax Smoke"])
                _names.append(["7B9F80", "Amulet"])
                _names.append(["7BA05B", "Asparagus"])
                _names.append(["7C1C05", "Kenyan Copper"])
                _names.append(["7C7631", "Pesto"])
                _names.append(["7C778A", "Topaz"])
                _names.append(["7C7B7A", "Concord"])
                _names.append(["7C7B82", "Jumbo"])
                _names.append(["7C881A", "Trendy Green"])
                _names.append(["7CA1A6", "Gumbo"])
                _names.append(["7CB0A1", "Acapulco"])
                _names.append(["7CB7BB", "Neptune"])
                _names.append(["7D2C14", "Pueblo"])
                _names.append(["7DA98D", "Bay Leaf"])
                _names.append(["7DC8F7", "Malibu"])
                _names.append(["7DD8C6", "Bermuda"])
                _names.append(["7E3A15", "Copper Canyon"])
                _names.append(["7F1734", "Claret"])
                _names.append(["7F3A02", "Peru Tan"])
                _names.append(["7F626D", "Falcon"])
                _names.append(["7F7589", "Mobster"])
                _names.append(["7F76D3", "Moody Blue"])
                _names.append(["7FFF00", "Chartreuse"])
                _names.append(["7FFFD4", "Aquamarine"])
                _names.append(["800000", "Maroon"])
                _names.append(["800B47", "Rose Bud Cherry"])
                _names.append(["801818", "Falu Red"])
                _names.append(["80341F", "Red Robin"])
                _names.append(["803790", "Vivid Violet"])
                _names.append(["80461B", "Russet"])
                _names.append(["807E79", "Friar Gray"])
                _names.append(["808000", "Olive"])
                _names.append(["808080", "Gray"])
                _names.append(["80B3AE", "Gulf Stream"])
                _names.append(["80B3C4", "Glacier"])
                _names.append(["80CCEA", "Seagull"])
                _names.append(["81422C", "Nutmeg"])
                _names.append(["816E71", "Spicy Pink"])
                _names.append(["817377", "Empress"])
                _names.append(["819885", "Spanish Green"])
                _names.append(["826F65", "Sand Dune"])
                _names.append(["828685", "Gunsmoke"])
                _names.append(["828F72", "Battleship Gray"])
                _names.append(["831923", "Merlot"])
                _names.append(["837050", "Shadow"])
                _names.append(["83AA5D", "Chelsea Cucumber"])
                _names.append(["83D0C6", "Monte Carlo"])
                _names.append(["843179", "Plum"])
                _names.append(["84A0A0", "Granny Smith"])
                _names.append(["8581D9", "Chetwode Blue"])
                _names.append(["858470", "Bandicoot"])
                _names.append(["859FAF", "Bali Hai"])
                _names.append(["85C4CC", "Half Baked"])
                _names.append(["860111", "Red Devil"])
                _names.append(["863C3C", "Lotus"])
                _names.append(["86483C", "Ironstone"])
                _names.append(["864D1E", "Bull Shot"])
                _names.append(["86560A", "Rusty Nail"])
                _names.append(["868974", "Bitter"])
                _names.append(["86949F", "Regent Gray"])
                _names.append(["871550", "Disco"])
                _names.append(["87756E", "Americano"])
                _names.append(["877C7B", "Hurricane"])
                _names.append(["878D91", "Oslo Gray"])
                _names.append(["87AB39", "Sushi"])
                _names.append(["885342", "Spicy Mix"])
                _names.append(["886221", "Kumera"])
                _names.append(["888387", "Suva Gray"])
                _names.append(["888D65", "Avocado"])
                _names.append(["893456", "Camelot"])
                _names.append(["893843", "Solid Pink"])
                _names.append(["894367", "Cannon Pink"])
                _names.append(["897D6D", "Makara"])
                _names.append(["8A3324", "Burnt Umber"])
                _names.append(["8A73D6", "True V"])
                _names.append(["8A8360", "Clay Creek"])
                _names.append(["8A8389", "Monsoon"])
                _names.append(["8A8F8A", "Stack"])
                _names.append(["8AB9F1", "Jordy Blue"])
                _names.append(["8B00FF", "Electric Violet"])
                _names.append(["8B0723", "Monarch"])
                _names.append(["8B6B0B", "Corn Harvest"])
                _names.append(["8B8470", "Olive Haze"])
                _names.append(["8B847E", "Schooner"])
                _names.append(["8B8680", "Natural Gray"])
                _names.append(["8B9C90", "Mantle"])
                _names.append(["8B9FEE", "Portage"])
                _names.append(["8BA690", "Envy"])
                _names.append(["8BA9A5", "Cascade"])
                _names.append(["8BE6D8", "Riptide"])
                _names.append(["8C055E", "Cardinal Pink"])
                _names.append(["8C472F", "Mule Fawn"])
                _names.append(["8C5738", "Potters Clay"])
                _names.append(["8C6495", "Trendy Pink"])
                _names.append(["8D0226", "Paprika"])
                _names.append(["8D3D38", "Sanguine Brown"])
                _names.append(["8D3F3F", "Tosca"])
                _names.append(["8D7662", "Cement"])
                _names.append(["8D8974", "Granite Green"])
                _names.append(["8D90A1", "Manatee"])
                _names.append(["8DA8CC", "Polo Blue"])
                _names.append(["8E0000", "Red Berry"])
                _names.append(["8E4D1E", "Rope"])
                _names.append(["8E6F70", "Opium"])
                _names.append(["8E775E", "Domino"])
                _names.append(["8E8190", "Mamba"])
                _names.append(["8EABC1", "Nepal"])
                _names.append(["8F021C", "Pohutukawa"])
                _names.append(["8F3E33", "El Salva"])
                _names.append(["8F4B0E", "Korma"])
                _names.append(["8F8176", "Squirrel"])
                _names.append(["8FD6B4", "Vista Blue"])
                _names.append(["900020", "Burgundy"])
                _names.append(["901E1E", "Old Brick"])
                _names.append(["907874", "Hemp"])
                _names.append(["907B71", "Almond Frost"])
                _names.append(["908D39", "Sycamore"])
                _names.append(["92000A", "Sangria"])
                _names.append(["924321", "Cumin"])
                _names.append(["926F5B", "Beaver"])
                _names.append(["928573", "Stonewall"])
                _names.append(["928590", "Venus"])
                _names.append(["9370DB", "Medium Purple"])
                _names.append(["93CCEA", "Cornflower"])
                _names.append(["93DFB8", "Algae Green"])
                _names.append(["944747", "Copper Rust"])
                _names.append(["948771", "Arrowtown"])
                _names.append(["950015", "Scarlett"])
                _names.append(["956387", "Strikemaster"])
                _names.append(["959396", "Mountain Mist"])
                _names.append(["960018", "Carmine"])
                _names.append(["964B00", "Brown"])
                _names.append(["967059", "Leather"])
                _names.append(["9678B6", "Purple Mountain's Majesty"])
                _names.append(["967BB6", "Lavender Purple"])
                _names.append(["96A8A1", "Pewter"])
                _names.append(["96BBAB", "Summer Green"])
                _names.append(["97605D", "Au Chico"])
                _names.append(["9771B5", "Wisteria"])
                _names.append(["97CD2D", "Atlantis"])
                _names.append(["983D61", "Vin Rouge"])
                _names.append(["9874D3", "Lilac Bush"])
                _names.append(["98777B", "Bazaar"])
                _names.append(["98811B", "Hacienda"])
                _names.append(["988D77", "Pale Oyster"])
                _names.append(["98FF98", "Mint Green"])
                _names.append(["990066", "Fresh Eggplant"])
                _names.append(["991199", "Violet Eggplant"])
                _names.append(["991613", "Tamarillo"])
                _names.append(["991B07", "Totem Pole"])
                _names.append(["996666", "Copper Rose"])
                _names.append(["9966CC", "Amethyst"])
                _names.append(["997A8D", "Mountbatten Pink"])
                _names.append(["9999CC", "Blue Bell"])
                _names.append(["9A3820", "Prairie Sand"])
                _names.append(["9A6E61", "Toast"])
                _names.append(["9A9577", "Gurkha"])
                _names.append(["9AB973", "Olivine"])
                _names.append(["9AC2B8", "Shadow Green"])
                _names.append(["9B4703", "Oregon"])
                _names.append(["9B9E8F", "Lemon Grass"])
                _names.append(["9C3336", "Stiletto"])
                _names.append(["9D5616", "Hawaiian Tan"])
                _names.append(["9DACB7", "Gull Gray"])
                _names.append(["9DC209", "Pistachio"])
                _names.append(["9DE093", "Granny Smith Apple"])
                _names.append(["9DE5FF", "Anakiwa"])
                _names.append(["9E5302", "Chelsea Gem"])
                _names.append(["9E5B40", "Sepia Skin"])
                _names.append(["9EA587", "Sage"])
                _names.append(["9EA91F", "Citron"])
                _names.append(["9EB1CD", "Rock Blue"])
                _names.append(["9EDEE0", "Morning Glory"])
                _names.append(["9F381D", "Cognac"])
                _names.append(["9F821C", "Reef Gold"])
                _names.append(["9F9F9C", "Star Dust"])
                _names.append(["9FA0B1", "Santas Gray"])
                _names.append(["9FD7D3", "Sinbad"])
                _names.append(["9FDD8C", "Feijoa"])
                _names.append(["A02712", "Tabasco"])
                _names.append(["A1750D", "Buttered Rum"])
                _names.append(["A1ADB5", "Hit Gray"])
                _names.append(["A1C50A", "Citrus"])
                _names.append(["A1DAD7", "Aqua Island"])
                _names.append(["A1E9DE", "Water Leaf"])
                _names.append(["A2006D", "Flirt"])
                _names.append(["A23B6C", "Rouge"])
                _names.append(["A26645", "Cape Palliser"])
                _names.append(["A2AAB3", "Gray Chateau"])
                _names.append(["A2AEAB", "Edward"])
                _names.append(["A3807B", "Pharlap"])
                _names.append(["A397B4", "Amethyst Smoke"])
                _names.append(["A3E3ED", "Blizzard Blue"])
                _names.append(["A4A49D", "Delta"])
                _names.append(["A4A6D3", "Wistful"])
                _names.append(["A4AF6E", "Green Smoke"])
                _names.append(["A50B5E", "Jazzberry Jam"])
                _names.append(["A59B91", "Zorba"])
                _names.append(["A5CB0C", "Bahia"])
                _names.append(["A62F20", "Roof Terracotta"])
                _names.append(["A65529", "Paarl"])
                _names.append(["A68B5B", "Barley Corn"])
                _names.append(["A69279", "Donkey Brown"])
                _names.append(["A6A29A", "Dawn"])
                _names.append(["A72525", "Mexican Red"])
                _names.append(["A7882C", "Luxor Gold"])
                _names.append(["A85307", "Rich Gold"])
                _names.append(["A86515", "Reno Sand"])
                _names.append(["A86B6B", "Coral Tree"])
                _names.append(["A8989B", "Dusty Gray"])
                _names.append(["A899E6", "Dull Lavender"])
                _names.append(["A8A589", "Tallow"])
                _names.append(["A8AE9C", "Bud"])
                _names.append(["A8AF8E", "Locust"])
                _names.append(["A8BD9F", "Norway"])
                _names.append(["A8E3BD", "Chinook"])
                _names.append(["A9A491", "Gray Olive"])
                _names.append(["A9ACB6", "Aluminium"])
                _names.append(["A9B2C3", "Cadet Blue"])
                _names.append(["A9B497", "Schist"])
                _names.append(["A9BDBF", "Tower Gray"])
                _names.append(["A9BEF2", "Perano"])
                _names.append(["A9C6C2", "Opal"])
                _names.append(["AA375A", "Night Shadz"])
                _names.append(["AA4203", "Fire"])
                _names.append(["AA8B5B", "Muesli"])
                _names.append(["AA8D6F", "Sandal"])
                _names.append(["AAA5A9", "Shady Lady"])
                _names.append(["AAA9CD", "Logan"])
                _names.append(["AAABB7", "Spun Pearl"])
                _names.append(["AAD6E6", "Regent St Blue"])
                _names.append(["AAF0D1", "Magic Mint"])
                _names.append(["AB0563", "Lipstick"])
                _names.append(["AB3472", "Royal Heath"])
                _names.append(["AB917A", "Sandrift"])
                _names.append(["ABA0D9", "Cold Purple"])
                _names.append(["ABA196", "Bronco"])
                _names.append(["AC8A56", "Limed Oak"])
                _names.append(["AC91CE", "East Side"])
                _names.append(["AC9E22", "Lemon Ginger"])
                _names.append(["ACA494", "Napa"])
                _names.append(["ACA586", "Hillary"])
                _names.append(["ACA59F", "Cloudy"])
                _names.append(["ACACAC", "Silver Chalice"])
                _names.append(["ACB78E", "Swamp Green"])
                _names.append(["ACCBB1", "Spring Rain"])
                _names.append(["ACDD4D", "Conifer"])
                _names.append(["ACE1AF", "Celadon"])
                _names.append(["AD781B", "Mandalay"])
                _names.append(["ADBED1", "Casper"])
                _names.append(["ADDFAD", "Moss Green"])
                _names.append(["ADE6C4", "Padua"])
                _names.append(["ADFF2F", "Green Yellow"])
                _names.append(["AE4560", "Hippie Pink"])
                _names.append(["AE6020", "Desert"])
                _names.append(["AE809E", "Bouquet"])
                _names.append(["AF4035", "Medium Carmine"])
                _names.append(["AF4D43", "Apple Blossom"])
                _names.append(["AF593E", "Brown Rust"])
                _names.append(["AF8751", "Driftwood"])
                _names.append(["AF8F2C", "Alpine"])
                _names.append(["AF9F1C", "Lucky"])
                _names.append(["AFA09E", "Martini"])
                _names.append(["AFB1B8", "Bombay"])
                _names.append(["AFBDD9", "Pigeon Post"])
                _names.append(["B04C6A", "Cadillac"])
                _names.append(["B05D54", "Matrix"])
                _names.append(["B05E81", "Tapestry"])
                _names.append(["B06608", "Mai Tai"])
                _names.append(["B09A95", "Del Rio"])
                _names.append(["B0E0E6", "Powder Blue"])
                _names.append(["B0E313", "Inch Worm"])
                _names.append(["B10000", "Bright Red"])
                _names.append(["B14A0B", "Vesuvius"])
                _names.append(["B1610B", "Pumpkin Skin"])
                _names.append(["B16D52", "Santa Fe"])
                _names.append(["B19461", "Teak"])
                _names.append(["B1E2C1", "Fringy Flower"])
                _names.append(["B1F4E7", "Ice Cold"])
                _names.append(["B20931", "Shiraz"])
                _names.append(["B2A1EA", "Biloba Flower"])
                _names.append(["B32D29", "Tall Poppy"])
                _names.append(["B35213", "Fiery Orange"])
                _names.append(["B38007", "Hot Toddy"])
                _names.append(["B3AF95", "Taupe Gray"])
                _names.append(["B3C110", "La Rioja"])
                _names.append(["B43332", "Well Read"])
                _names.append(["B44668", "Blush"])
                _names.append(["B4CFD3", "Jungle Mist"])
                _names.append(["B57281", "Turkish Rose"])
                _names.append(["B57EDC", "Lavender"])
                _names.append(["B5A27F", "Mongoose"])
                _names.append(["B5B35C", "Olive Green"])
                _names.append(["B5D2CE", "Jet Stream"])
                _names.append(["B5ECDF", "Cruise"])
                _names.append(["B6316C", "Hibiscus"])
                _names.append(["B69D98", "Thatch"])
                _names.append(["B6B095", "Heathered Gray"])
                _names.append(["B6BAA4", "Eagle"])
                _names.append(["B6D1EA", "Spindle"])
                _names.append(["B6D3BF", "Gum Leaf"])
                _names.append(["B7410E", "Rust"])
                _names.append(["B78E5C", "Muddy Waters"])
                _names.append(["B7A214", "Sahara"])
                _names.append(["B7A458", "Husk"])
                _names.append(["B7B1B1", "Nobel"])
                _names.append(["B7C3D0", "Heather"])
                _names.append(["B7F0BE", "Madang"])
                _names.append(["B81104", "Milano Red"])
                _names.append(["B87333", "Copper"])
                _names.append(["B8B56A", "Gimblet"])
                _names.append(["B8C1B1", "Green Spring"])
                _names.append(["B8C25D", "Celery"])
                _names.append(["B8E0F9", "Sail"])
                _names.append(["B94E48", "Chestnut"])
                _names.append(["B95140", "Crail"])
                _names.append(["B98D28", "Marigold"])
                _names.append(["B9C46A", "Wild Willow"])
                _names.append(["B9C8AC", "Rainee"])
                _names.append(["BA0101", "Guardsman Red"])
                _names.append(["BA450C", "Rock Spray"])
                _names.append(["BA6F1E", "Bourbon"])
                _names.append(["BA7F03", "Pirate Gold"])
                _names.append(["BAB1A2", "Nomad"])
                _names.append(["BAC7C9", "Submarine"])
                _names.append(["BAEEF9", "Charlotte"])
                _names.append(["BB3385", "Medium Red Violet"])
                _names.append(["BB8983", "Brandy Rose"])
                _names.append(["BBD009", "Rio Grande"])
                _names.append(["BBD7C1", "Surf"])
                _names.append(["BCC9C2", "Powder Ash"])
                _names.append(["BD5E2E", "Tuscany"])
                _names.append(["BD978E", "Quicksand"])
                _names.append(["BDB1A8", "Silk"])
                _names.append(["BDB2A1", "Malta"])
                _names.append(["BDB3C7", "Chatelle"])
                _names.append(["BDBBD7", "Lavender Gray"])
                _names.append(["BDBDC6", "French Gray"])
                _names.append(["BDC8B3", "Clay Ash"])
                _names.append(["BDC9CE", "Loblolly"])
                _names.append(["BDEDFD", "French Pass"])
                _names.append(["BEA6C3", "London Hue"])
                _names.append(["BEB5B7", "Pink Swan"])
                _names.append(["BEDE0D", "Fuego"])
                _names.append(["BF5500", "Rose of Sharon"])
                _names.append(["BFB8B0", "Tide"])
                _names.append(["BFBED8", "Blue Haze"])
                _names.append(["BFC1C2", "Silver Sand"])
                _names.append(["BFC921", "Key Lime Pie"])
                _names.append(["BFDBE2", "Ziggurat"])
                _names.append(["BFFF00", "Lime"])
                _names.append(["C02B18", "Thunderbird"])
                _names.append(["C04737", "Mojo"])
                _names.append(["C08081", "Old Rose"])
                _names.append(["C0C0C0", "Silver"])
                _names.append(["C0D3B9", "Pale Leaf"])
                _names.append(["C0D8B6", "Pixie Green"])
                _names.append(["C1440E", "Tia Maria"])
                _names.append(["C154C1", "Fuchsia Pink"])
                _names.append(["C1A004", "Buddha Gold"])
                _names.append(["C1B7A4", "Bison Hide"])
                _names.append(["C1BAB0", "Tea"])
                _names.append(["C1BECD", "Gray Suit"])
                _names.append(["C1D7B0", "Sprout"])
                _names.append(["C1F07C", "Sulu"])
                _names.append(["C26B03", "Indochine"])
                _names.append(["C2955D", "Twine"])
                _names.append(["C2BDB6", "Cotton Seed"])
                _names.append(["C2CAC4", "Pumice"])
                _names.append(["C2E8E5", "Jagged Ice"])
                _names.append(["C32148", "Maroon Flush"])
                _names.append(["C3B091", "Indian Khaki"])
                _names.append(["C3BFC1", "Pale Slate"])
                _names.append(["C3C3BD", "Gray Nickel"])
                _names.append(["C3CDE6", "Periwinkle Gray"])
                _names.append(["C3D1D1", "Tiara"])
                _names.append(["C3DDF9", "Tropical Blue"])
                _names.append(["C41E3A", "Cardinal"])
                _names.append(["C45655", "Fuzzy Wuzzy Brown"])
                _names.append(["C45719", "Orange Roughy"])
                _names.append(["C4C4BC", "Mist Gray"])
                _names.append(["C4D0B0", "Coriander"])
                _names.append(["C4F4EB", "Mint Tulip"])
                _names.append(["C54B8C", "Mulberry"])
                _names.append(["C59922", "Nugget"])
                _names.append(["C5994B", "Tussock"])
                _names.append(["C5DBCA", "Sea Mist"])
                _names.append(["C5E17A", "Yellow Green"])
                _names.append(["C62D42", "Brick Red"])
                _names.append(["C6726B", "Contessa"])
                _names.append(["C69191", "Oriental Pink"])
                _names.append(["C6A84B", "Roti"])
                _names.append(["C6C3B5", "Ash"])
                _names.append(["C6C8BD", "Kangaroo"])
                _names.append(["C6E610", "Las Palmas"])
                _names.append(["C7031E", "Monza"])
                _names.append(["C71585", "Red Violet"])
                _names.append(["C7BCA2", "Coral Reef"])
                _names.append(["C7C1FF", "Melrose"])
                _names.append(["C7C4BF", "Cloud"])
                _names.append(["C7C9D5", "Ghost"])
                _names.append(["C7CD90", "Pine Glade"])
                _names.append(["C7DDE5", "Botticelli"])
                _names.append(["C88A65", "Antique Brass"])
                _names.append(["C8A2C8", "Lilac"])
                _names.append(["C8A528", "Hokey Pokey"])
                _names.append(["C8AABF", "Lily"])
                _names.append(["C8B568", "Laser"])
                _names.append(["C8E3D7", "Edgewater"])
                _names.append(["C96323", "Piper"])
                _names.append(["C99415", "Pizza"])
                _names.append(["C9A0DC", "Light Wisteria"])
                _names.append(["C9B29B", "Rodeo Dust"])
                _names.append(["C9B35B", "Sundance"])
                _names.append(["C9B93B", "Earls Green"])
                _names.append(["C9C0BB", "Silver Rust"])
                _names.append(["C9D9D2", "Conch"])
                _names.append(["C9FFA2", "Reef"])
                _names.append(["C9FFE5", "Aero Blue"])
                _names.append(["CA3435", "Flush Mahogany"])
                _names.append(["CABB48", "Turmeric"])
                _names.append(["CADCD4", "Paris White"])
                _names.append(["CAE00D", "Bitter Lemon"])
                _names.append(["CAE6DA", "Skeptic"])
                _names.append(["CB8FA9", "Viola"])
                _names.append(["CBCAB6", "Foggy Gray"])
                _names.append(["CBD3B0", "Green Mist"])
                _names.append(["CBDBD6", "Nebula"])
                _names.append(["CC3333", "Persian Red"])
                _names.append(["CC5500", "Burnt Orange"])
                _names.append(["CC7722", "Ochre"])
                _names.append(["CC8899", "Puce"])
                _names.append(["CCCAA8", "Thistle Green"])
                _names.append(["CCCCFF", "Periwinkle"])
                _names.append(["CCFF00", "Electric Lime"])
                _names.append(["CD5700", "Tenn"])
                _names.append(["CD5C5C", "Chestnut Rose"])
                _names.append(["CD8429", "Brandy Punch"])
                _names.append(["CDF4FF", "Onahau"])
                _names.append(["CEB98F", "Sorrell Brown"])
                _names.append(["CEBABA", "Cold Turkey"])
                _names.append(["CEC291", "Yuma"])
                _names.append(["CEC7A7", "Chino"])
                _names.append(["CFA39D", "Eunry"])
                _names.append(["CFB53B", "Old Gold"])
                _names.append(["CFDCCF", "Tasman"])
                _names.append(["CFE5D2", "Surf Crest"])
                _names.append(["CFF9F3", "Humming Bird"])
                _names.append(["CFFAF4", "Scandal"])
                _names.append(["D05F04", "Red Stage"])
                _names.append(["D06DA1", "Hopbush"])
                _names.append(["D07D12", "Meteor"])
                _names.append(["D0BEF8", "Perfume"])
                _names.append(["D0C0E5", "Prelude"])
                _names.append(["D0F0C0", "Tea Green"])
                _names.append(["D18F1B", "Geebung"])
                _names.append(["D1BEA8", "Vanilla"])
                _names.append(["D1C6B4", "Soft Amber"])
                _names.append(["D1D2CA", "Celeste"])
                _names.append(["D1D2DD", "Mischka"])
                _names.append(["D1E231", "Pear"])
                _names.append(["D2691E", "Hot Cinnamon"])
                _names.append(["D27D46", "Raw Sienna"])
                _names.append(["D29EAA", "Careys Pink"])
                _names.append(["D2B48C", "Tan"])
                _names.append(["D2DA97", "Deco"])
                _names.append(["D2F6DE", "Blue Romance"])
                _names.append(["D2F8B0", "Gossip"])
                _names.append(["D3CBBA", "Sisal"])
                _names.append(["D3CDC5", "Swirl"])
                _names.append(["D47494", "Charm"])
                _names.append(["D4B6AF", "Clam Shell"])
                _names.append(["D4BF8D", "Straw"])
                _names.append(["D4C4A8", "Akaroa"])
                _names.append(["D4CD16", "Bird Flower"])
                _names.append(["D4D7D9", "Iron"])
                _names.append(["D4DFE2", "Geyser"])
                _names.append(["D4E2FC", "Hawkes Blue"])
                _names.append(["D54600", "Grenadier"])
                _names.append(["D591A4", "Can Can"])
                _names.append(["D59A6F", "Whiskey"])
                _names.append(["D5D195", "Winter Hazel"])
                _names.append(["D5F6E3", "Granny Apple"])
                _names.append(["D69188", "My Pink"])
                _names.append(["D6C562", "Tacha"])
                _names.append(["D6CEF6", "Moon Raker"])
                _names.append(["D6D6D1", "Quill Gray"])
                _names.append(["D6FFDB", "Snowy Mint"])
                _names.append(["D7837F", "New York Pink"])
                _names.append(["D7C498", "Pavlova"])
                _names.append(["D7D0FF", "Fog"])
                _names.append(["D84437", "Valencia"])
                _names.append(["D87C63", "Japonica"])
                _names.append(["D8BFD8", "Thistle"])
                _names.append(["D8C2D5", "Maverick"])
                _names.append(["D8FCFA", "Foam"])
                _names.append(["D94972", "Cabaret"])
                _names.append(["D99376", "Burning Sand"])
                _names.append(["D9B99B", "Cameo"])
                _names.append(["D9D6CF", "Timberwolf"])
                _names.append(["D9DCC1", "Tana"])
                _names.append(["D9E4F5", "Link Water"])
                _names.append(["D9F7FF", "Mabel"])
                _names.append(["DA3287", "Cerise"])
                _names.append(["DA5B38", "Flame Pea"])
                _names.append(["DA6304", "Bamboo"])
                _names.append(["DA6A41", "Red Damask"])
                _names.append(["DA70D6", "Orchid"])
                _names.append(["DA8A67", "Copperfield"])
                _names.append(["DAA520", "Golden Grass"])
                _names.append(["DAECD6", "Zanah"])
                _names.append(["DAF4F0", "Iceberg"])
                _names.append(["DAFAFF", "Oyster Bay"])
                _names.append(["DB5079", "Cranberry"])
                _names.append(["DB9690", "Petite Orchid"])
                _names.append(["DB995E", "Di Serria"])
                _names.append(["DBDBDB", "Alto"])
                _names.append(["DBFFF8", "Frosted Mint"])
                _names.append(["DC143C", "Crimson"])
                _names.append(["DC4333", "Punch"])
                _names.append(["DCB20C", "Galliano"])
                _names.append(["DCB4BC", "Blossom"])
                _names.append(["DCD747", "Wattle"])
                _names.append(["DCD9D2", "Westar"])
                _names.append(["DCDDCC", "Moon Mist"])
                _names.append(["DCEDB4", "Caper"])
                _names.append(["DCF0EA", "Swans Down"])
                _names.append(["DDD6D5", "Swiss Coffee"])
                _names.append(["DDF9F1", "White Ice"])
                _names.append(["DE3163", "Cerise Red"])
                _names.append(["DE6360", "Roman"])
                _names.append(["DEA681", "Tumbleweed"])
                _names.append(["DEBA13", "Gold Tips"])
                _names.append(["DEC196", "Brandy"])
                _names.append(["DECBC6", "Wafer"])
                _names.append(["DED4A4", "Sapling"])
                _names.append(["DED717", "Barberry"])
                _names.append(["DEE5C0", "Beryl Green"])
                _names.append(["DEF5FF", "Pattens Blue"])
                _names.append(["DF73FF", "Heliotrope"])
                _names.append(["DFBE6F", "Apache"])
                _names.append(["DFCD6F", "Chenin"])
                _names.append(["DFCFDB", "Lola"])
                _names.append(["DFECDA", "Willow Brook"])
                _names.append(["DFFF00", "Chartreuse Yellow"])
                _names.append(["E0B0FF", "Mauve"])
                _names.append(["E0B646", "Anzac"])
                _names.append(["E0B974", "Harvest Gold"])
                _names.append(["E0C095", "Calico"])
                _names.append(["E0FFFF", "Baby Blue"])
                _names.append(["E16865", "Sunglo"])
                _names.append(["E1BC64", "Equator"])
                _names.append(["E1C0C8", "Pink Flare"])
                _names.append(["E1E6D6", "Periglacial Blue"])
                _names.append(["E1EAD4", "Kidnapper"])
                _names.append(["E1F6E8", "Tara"])
                _names.append(["E25465", "Mandy"])
                _names.append(["E2725B", "Terracotta"])
                _names.append(["E28913", "Golden Bell"])
                _names.append(["E292C0", "Shocking"])
                _names.append(["E29418", "Dixie"])
                _names.append(["E29CD2", "Light Orchid"])
                _names.append(["E2D8ED", "Snuff"])
                _names.append(["E2EBED", "Mystic"])
                _names.append(["E2F3EC", "Apple Green"])
                _names.append(["E30B5C", "Razzmatazz"])
                _names.append(["E32636", "Alizarin Crimson"])
                _names.append(["E34234", "Cinnabar"])
                _names.append(["E3BEBE", "Cavern Pink"])
                _names.append(["E3F5E1", "Peppermint"])
                _names.append(["E3F988", "Mindaro"])
                _names.append(["E47698", "Deep Blush"])
                _names.append(["E49B0F", "Gamboge"])
                _names.append(["E4C2D5", "Melanie"])
                _names.append(["E4CFDE", "Twilight"])
                _names.append(["E4D1C0", "Bone"])
                _names.append(["E4D422", "Sunflower"])
                _names.append(["E4D5B7", "Grain Brown"])
                _names.append(["E4D69B", "Zombie"])
                _names.append(["E4F6E7", "Frostee"])
                _names.append(["E4FFD1", "Snow Flurry"])
                _names.append(["E52B50", "Amaranth"])
                _names.append(["E5841B", "Zest"])
                _names.append(["E5CCC9", "Dust Storm"])
                _names.append(["E5D7BD", "Stark White"])
                _names.append(["E5D8AF", "Hampton"])
                _names.append(["E5E0E1", "Bon Jour"])
                _names.append(["E5E5E5", "Mercury"])
                _names.append(["E5F9F6", "Polar"])
                _names.append(["E64E03", "Trinidad"])
                _names.append(["E6BE8A", "Gold Sand"])
                _names.append(["E6BEA5", "Cashmere"])
                _names.append(["E6D7B9", "Double Spanish White"])
                _names.append(["E6E4D4", "Satin Linen"])
                _names.append(["E6F2EA", "Harp"])
                _names.append(["E6F8F3", "Off Green"])
                _names.append(["E6FFE9", "Hint of Green"])
                _names.append(["E6FFFF", "Tranquil"])
                _names.append(["E77200", "Mango Tango"])
                _names.append(["E7730A", "Christine"])
                _names.append(["E79F8C", "Tonys Pink"])
                _names.append(["E79FC4", "Kobi"])
                _names.append(["E7BCB4", "Rose Fog"])
                _names.append(["E7BF05", "Corn"])
                _names.append(["E7CD8C", "Putty"])
                _names.append(["E7ECE6", "Gray Nurse"])
                _names.append(["E7F8FF", "Lily White"])
                _names.append(["E7FEFF", "Bubbles"])
                _names.append(["E89928", "Fire Bush"])
                _names.append(["E8B9B3", "Shilo"])
                _names.append(["E8E0D5", "Pearl Bush"])
                _names.append(["E8EBE0", "Green White"])
                _names.append(["E8F1D4", "Chrome White"])
                _names.append(["E8F2EB", "Gin"])
                _names.append(["E8F5F2", "Aqua Squeeze"])
                _names.append(["E96E00", "Clementine"])
                _names.append(["E97451", "Burnt Sienna"])
                _names.append(["E97C07", "Tahiti Gold"])
                _names.append(["E9CECD", "Oyster Pink"])
                _names.append(["E9D75A", "Confetti"])
                _names.append(["E9E3E3", "Ebb"])
                _names.append(["E9F8ED", "Ottoman"])
                _names.append(["E9FFFD", "Clear Day"])
                _names.append(["EA88A8", "Carissma"])
                _names.append(["EAAE69", "Porsche"])
                _names.append(["EAB33B", "Tulip Tree"])
                _names.append(["EAC674", "Rob Roy"])
                _names.append(["EADAB8", "Raffia"])
                _names.append(["EAE8D4", "White Rock"])
                _names.append(["EAF6EE", "Panache"])
                _names.append(["EAF6FF", "Solitude"])
                _names.append(["EAF9F5", "Aqua Spring"])
                _names.append(["EAFFFE", "Dew"])
                _names.append(["EB9373", "Apricot"])
                _names.append(["EBC2AF", "Zinnwaldite"])
                _names.append(["ECA927", "Fuel Yellow"])
                _names.append(["ECC54E", "Ronchi"])
                _names.append(["ECC7EE", "French Lilac"])
                _names.append(["ECCDB9", "Just Right"])
                _names.append(["ECE090", "Wild Rice"])
                _names.append(["ECEBBD", "Fall Green"])
                _names.append(["ECEBCE", "Aths Special"])
                _names.append(["ECF245", "Starship"])
                _names.append(["ED0A3F", "Red Ribbon"])
                _names.append(["ED7A1C", "Tango"])
                _names.append(["ED9121", "Carrot Orange"])
                _names.append(["ED989E", "Sea Pink"])
                _names.append(["EDB381", "Tacao"])
                _names.append(["EDC9AF", "Desert Sand"])
                _names.append(["EDCDAB", "Pancho"])
                _names.append(["EDDCB1", "Chamois"])
                _names.append(["EDEA99", "Primrose"])
                _names.append(["EDF5DD", "Frost"])
                _names.append(["EDF5F5", "Aqua Haze"])
                _names.append(["EDF6FF", "Zumthor"])
                _names.append(["EDF9F1", "Narvik"])
                _names.append(["EDFC84", "Honeysuckle"])
                _names.append(["EE82EE", "Lavender Magenta"])
                _names.append(["EEC1BE", "Beauty Bush"])
                _names.append(["EED794", "Chalky"])
                _names.append(["EED9C4", "Almond"])
                _names.append(["EEDC82", "Flax"])
                _names.append(["EEDEDA", "Bizarre"])
                _names.append(["EEE3AD", "Double Colonial White"])
                _names.append(["EEEEE8", "Cararra"])
                _names.append(["EEEF78", "Manz"])
                _names.append(["EEF0C8", "Tahuna Sands"])
                _names.append(["EEF0F3", "Athens Gray"])
                _names.append(["EEF3C3", "Tusk"])
                _names.append(["EEF4DE", "Loafer"])
                _names.append(["EEF6F7", "Catskill White"])
                _names.append(["EEFDFF", "Twilight Blue"])
                _names.append(["EEFF9A", "Jonquil"])
                _names.append(["EEFFE2", "Rice Flower"])
                _names.append(["EF863F", "Jaffa"])
                _names.append(["EFEFEF", "Gallery"])
                _names.append(["EFF2F3", "Porcelain"])
                _names.append(["F091A9", "Mauvelous"])
                _names.append(["F0D52D", "Golden Dream"])
                _names.append(["F0DB7D", "Golden Sand"])
                _names.append(["F0DC82", "Buff"])
                _names.append(["F0E2EC", "Prim"])
                _names.append(["F0E68C", "Khaki"])
                _names.append(["F0EEFD", "Selago"])
                _names.append(["F0EEFF", "Titan White"])
                _names.append(["F0F8FF", "Alice Blue"])
                _names.append(["F0FCEA", "Feta"])
                _names.append(["F18200", "Gold Drop"])
                _names.append(["F19BAB", "Wewak"])
                _names.append(["F1E788", "Sahara Sand"])
                _names.append(["F1E9D2", "Parchment"])
                _names.append(["F1E9FF", "Blue Chalk"])
                _names.append(["F1EEC1", "Mint Julep"])
                _names.append(["F1F1F1", "Seashell"])
                _names.append(["F1F7F2", "Saltpan"])
                _names.append(["F1FFAD", "Tidal"])
                _names.append(["F1FFC8", "Chiffon"])
                _names.append(["F2552A", "Flamingo"])
                _names.append(["F28500", "Tangerine"])
                _names.append(["F2C3B2", "Mandys Pink"])
                _names.append(["F2F2F2", "Concrete"])
                _names.append(["F2FAFA", "Black Squeeze"])
                _names.append(["F34723", "Pomegranate"])
                _names.append(["F3AD16", "Buttercup"])
                _names.append(["F3D69D", "New Orleans"])
                _names.append(["F3D9DF", "Vanilla Ice"])
                _names.append(["F3E7BB", "Sidecar"])
                _names.append(["F3E9E5", "Dawn Pink"])
                _names.append(["F3EDCF", "Wheatfield"])
                _names.append(["F3FB62", "Canary"])
                _names.append(["F3FBD4", "Orinoco"])
                _names.append(["F3FFD8", "Carla"])
                _names.append(["F400A1", "Hollywood Cerise"])
                _names.append(["F4A460", "Sandy brown"])
                _names.append(["F4C430", "Saffron"])
                _names.append(["F4D81C", "Ripe Lemon"])
                _names.append(["F4EBD3", "Janna"])
                _names.append(["F4F2EE", "Pampas"])
                _names.append(["F4F4F4", "Wild Sand"])
                _names.append(["F4F8FF", "Zircon"])
                _names.append(["F57584", "Froly"])
                _names.append(["F5C85C", "Cream Can"])
                _names.append(["F5C999", "Manhattan"])
                _names.append(["F5D5A0", "Maize"])
                _names.append(["F5DEB3", "Wheat"])
                _names.append(["F5E7A2", "Sandwisp"])
                _names.append(["F5E7E2", "Pot Pourri"])
                _names.append(["F5E9D3", "Albescent White"])
                _names.append(["F5EDEF", "Soft Peach"])
                _names.append(["F5F3E5", "Ecru White"])
                _names.append(["F5F5DC", "Beige"])
                _names.append(["F5FB3D", "Golden Fizz"])
                _names.append(["F5FFBE", "Australian Mint"])
                _names.append(["F64A8A", "French Rose"])
                _names.append(["F653A6", "Brilliant Rose"])
                _names.append(["F6A4C9", "Illusion"])
                _names.append(["F6F0E6", "Merino"])
                _names.append(["F6F7F7", "Black Haze"])
                _names.append(["F6FFDC", "Spring Sun"])
                _names.append(["F7468A", "Violet Red"])
                _names.append(["F77703", "Chilean Fire"])
                _names.append(["F77FBE", "Persian Pink"])
                _names.append(["F7B668", "Rajah"])
                _names.append(["F7C8DA", "Azalea"])
                _names.append(["F7DBE6", "We Peep"])
                _names.append(["F7F2E1", "Quarter Spanish White"])
                _names.append(["F7F5FA", "Whisper"])
                _names.append(["F7FAF7", "Snow Drift"])
                _names.append(["F8B853", "Casablanca"])
                _names.append(["F8C3DF", "Chantilly"])
                _names.append(["F8D9E9", "Cherub"])
                _names.append(["F8DB9D", "Marzipan"])
                _names.append(["F8DD5C", "Energy Yellow"])
                _names.append(["F8E4BF", "Givry"])
                _names.append(["F8F0E8", "White Linen"])
                _names.append(["F8F4FF", "Magnolia"])
                _names.append(["F8F6F1", "Spring Wood"])
                _names.append(["F8F7DC", "Coconut Cream"])
                _names.append(["F8F7FC", "White Lilac"])
                _names.append(["F8F8F7", "Desert Storm"])
                _names.append(["F8F99C", "Texas"])
                _names.append(["F8FACD", "Corn Field"])
                _names.append(["F8FDD3", "Mimosa"])
                _names.append(["F95A61", "Carnation"])
                _names.append(["F9BF58", "Saffron Mango"])
                _names.append(["F9E0ED", "Carousel Pink"])
                _names.append(["F9E4BC", "Dairy Cream"])
                _names.append(["F9E663", "Portica"])
                _names.append(["F9EAF3", "Amour"])
                _names.append(["F9F8E4", "Rum Swizzle"])
                _names.append(["F9FF8B", "Dolly"])
                _names.append(["F9FFF6", "Sugar Cane"])
                _names.append(["FA7814", "Ecstasy"])
                _names.append(["FA9D5A", "Tan Hide"])
                _names.append(["FAD3A2", "Corvette"])
                _names.append(["FADFAD", "Peach Yellow"])
                _names.append(["FAE600", "Turbo"])
                _names.append(["FAEAB9", "Astra"])
                _names.append(["FAECCC", "Champagne"])
                _names.append(["FAF0E6", "Linen"])
                _names.append(["FAF3F0", "Fantasy"])
                _names.append(["FAF7D6", "Citrine White"])
                _names.append(["FAFAFA", "Alabaster"])
                _names.append(["FAFDE4", "Hint of Yellow"])
                _names.append(["FAFFA4", "Milan"])
                _names.append(["FB607F", "Brink Pink"])
                _names.append(["FB8989", "Geraldine"])
                _names.append(["FBA0E3", "Lavender Rose"])
                _names.append(["FBA129", "Sea Buckthorn"])
                _names.append(["FBAC13", "Sun"])
                _names.append(["FBAED2", "Lavender Pink"])
                _names.append(["FBB2A3", "Rose Bud"])
                _names.append(["FBBEDA", "Cupid"])
                _names.append(["FBCCE7", "Classic Rose"])
                _names.append(["FBCEB1", "Apricot Peach"])
                _names.append(["FBE7B2", "Banana Mania"])
                _names.append(["FBE870", "Marigold Yellow"])
                _names.append(["FBE96C", "Festival"])
                _names.append(["FBEA8C", "Sweet Corn"])
                _names.append(["FBEC5D", "Candy Corn"])
                _names.append(["FBF9F9", "Hint of Red"])
                _names.append(["FBFFBA", "Shalimar"])
                _names.append(["FC0FC0", "Shocking Pink"])
                _names.append(["FC80A5", "Tickle Me Pink"])
                _names.append(["FC9C1D", "Tree Poppy"])
                _names.append(["FCC01E", "Lightning Yellow"])
                _names.append(["FCD667", "Goldenrod"])
                _names.append(["FCD917", "Candlelight"])
                _names.append(["FCDA98", "Cherokee"])
                _names.append(["FCF4D0", "Double Pearl Lusta"])
                _names.append(["FCF4DC", "Pearl Lusta"])
                _names.append(["FCF8F7", "Vista White"])
                _names.append(["FCFBF3", "Bianca"])
                _names.append(["FCFEDA", "Moon Glow"])
                _names.append(["FCFFE7", "China Ivory"])
                _names.append(["FCFFF9", "Ceramic"])
                _names.append(["FD0E35", "Torch Red"])
                _names.append(["FD5B78", "Wild Watermelon"])
                _names.append(["FD7B33", "Crusta"])
                _names.append(["FD7C07", "Sorbus"])
                _names.append(["FD9FA2", "Sweet Pink"])
                _names.append(["FDD5B1", "Light Apricot"])
                _names.append(["FDD7E4", "Pig Pink"])
                _names.append(["FDE1DC", "Cinderella"])
                _names.append(["FDE295", "Golden Glow"])
                _names.append(["FDE910", "Lemon"])
                _names.append(["FDF5E6", "Old Lace"])
                _names.append(["FDF6D3", "Half Colonial White"])
                _names.append(["FDF7AD", "Drover"])
                _names.append(["FDFEB8", "Pale Prim"])
                _names.append(["FDFFD5", "Cumulus"])
                _names.append(["FE28A2", "Persian Rose"])
                _names.append(["FE4C40", "Sunset Orange"])
                _names.append(["FE6F5E", "Bittersweet"])
                _names.append(["FE9D04", "California"])
                _names.append(["FEA904", "Yellow Sea"])
                _names.append(["FEBAAD", "Melon"])
                _names.append(["FED33C", "Bright Sun"])
                _names.append(["FED85D", "Dandelion"])
                _names.append(["FEDB8D", "Salomie"])
                _names.append(["FEE5AC", "Cape Honey"])
                _names.append(["FEEBF3", "Remy"])
                _names.append(["FEEFCE", "Oasis"])
                _names.append(["FEF0EC", "Bridesmaid"])
                _names.append(["FEF2C7", "Beeswax"])
                _names.append(["FEF3D8", "Bleach White"])
                _names.append(["FEF4CC", "Pipi"])
                _names.append(["FEF4DB", "Half Spanish White"])
                _names.append(["FEF4F8", "Wisp Pink"])
                _names.append(["FEF5F1", "Provincial Pink"])
                _names.append(["FEF7DE", "Half Dutch White"])
                _names.append(["FEF8E2", "Solitaire"])
                _names.append(["FEF8FF", "White Pointer"])
                _names.append(["FEF9E3", "Off Yellow"])
                _names.append(["FEFCED", "Orange White"])
                _names.append(["FF0000", "Red"])
                _names.append(["FF007F", "Rose"])
                _names.append(["FF00CC", "Purple Pizzazz"])
                _names.append(["FF00FF", "Magenta / Fuchsia"])
                _names.append(["FF2400", "Scarlet"])
                _names.append(["FF3399", "Wild Strawberry"])
                _names.append(["FF33CC", "Razzle Dazzle Rose"])
                _names.append(["FF355E", "Radical Red"])
                _names.append(["FF3F34", "Red Orange"])
                _names.append(["FF4040", "Coral Red"])
                _names.append(["FF4D00", "Vermilion"])
                _names.append(["FF4F00", "International Orange"])
                _names.append(["FF6037", "Outrageous Orange"])
                _names.append(["FF6600", "Blaze Orange"])
                _names.append(["FF66FF", "Pink Flamingo"])
                _names.append(["FF681F", "Orange"])
                _names.append(["FF69B4", "Hot Pink"])
                _names.append(["FF6B53", "Persimmon"])
                _names.append(["FF6FFF", "Blush Pink"])
                _names.append(["FF7034", "Burning Orange"])
                _names.append(["FF7518", "Pumpkin"])
                _names.append(["FF7D07", "Flamenco"])
                _names.append(["FF7F00", "Flush Orange"])
                _names.append(["FF7F50", "Coral"])
                _names.append(["FF8C69", "Salmon"])
                _names.append(["FF9000", "Pizazz"])
                _names.append(["FF910F", "West Side"])
                _names.append(["FF91A4", "Pink Salmon"])
                _names.append(["FF9933", "Neon Carrot"])
                _names.append(["FF9966", "Atomic Tangerine"])
                _names.append(["FF9980", "Vivid Tangerine"])
                _names.append(["FF9E2C", "Sunshade"])
                _names.append(["FFA000", "Orange Peel"])
                _names.append(["FFA194", "Mona Lisa"])
                _names.append(["FFA500", "Web Orange"])
                _names.append(["FFA6C9", "Carnation Pink"])
                _names.append(["FFAB81", "Hit Pink"])
                _names.append(["FFAE42", "Yellow Orange"])
                _names.append(["FFB0AC", "Cornflower Lilac"])
                _names.append(["FFB1B3", "Sundown"])
                _names.append(["FFB31F", "My Sin"])
                _names.append(["FFB555", "Texas Rose"])
                _names.append(["FFB7D5", "Cotton Candy"])
                _names.append(["FFB97B", "Macaroni and Cheese"])
                _names.append(["FFBA00", "Selective Yellow"])
                _names.append(["FFBD5F", "Koromiko"])
                _names.append(["FFBF00", "Amber"])
                _names.append(["FFC0A8", "Wax Flower"])
                _names.append(["FFC0CB", "Pink"])
                _names.append(["FFC3C0", "Your Pink"])
                _names.append(["FFC901", "Supernova"])
                _names.append(["FFCBA4", "Flesh"])
                _names.append(["FFCC33", "Sunglow"])
                _names.append(["FFCC5C", "Golden Tainoi"])
                _names.append(["FFCC99", "Peach Orange"])
                _names.append(["FFCD8C", "Chardonnay"])
                _names.append(["FFD1DC", "Pastel Pink"])
                _names.append(["FFD2B7", "Romantic"])
                _names.append(["FFD38C", "Grandis"])
                _names.append(["FFD700", "Gold"])
                _names.append(["FFD800", "School bus Yellow"])
                _names.append(["FFD8D9", "Cosmos"])
                _names.append(["FFDB58", "Mustard"])
                _names.append(["FFDCD6", "Peach Schnapps"])
                _names.append(["FFDDAF", "Caramel"])
                _names.append(["FFDDCD", "Tuft Bush"])
                _names.append(["FFDDCF", "Watusi"])
                _names.append(["FFDDF4", "Pink Lace"])
                _names.append(["FFDEAD", "Navajo White"])
                _names.append(["FFDEB3", "Frangipani"])
                _names.append(["FFE1DF", "Pippin"])
                _names.append(["FFE1F2", "Pale Rose"])
                _names.append(["FFE2C5", "Negroni"])
                _names.append(["FFE5A0", "Cream Brulee"])
                _names.append(["FFE5B4", "Peach"])
                _names.append(["FFE6C7", "Tequila"])
                _names.append(["FFE772", "Kournikova"])
                _names.append(["FFEAC8", "Sandy Beach"])
                _names.append(["FFEAD4", "Karry"])
                _names.append(["FFEC13", "Broom"])
                _names.append(["FFEDBC", "Colonial White"])
                _names.append(["FFEED8", "Derby"])
                _names.append(["FFEFA1", "Vis Vis"])
                _names.append(["FFEFC1", "Egg White"])
                _names.append(["FFEFD5", "Papaya Whip"])
                _names.append(["FFEFEC", "Fair Pink"])
                _names.append(["FFF0DB", "Peach Cream"])
                _names.append(["FFF0F5", "Lavender blush"])
                _names.append(["FFF14F", "Gorse"])
                _names.append(["FFF1B5", "Buttermilk"])
                _names.append(["FFF1D8", "Pink Lady"])
                _names.append(["FFF1EE", "Forget Me Not"])
                _names.append(["FFF1F9", "Tutu"])
                _names.append(["FFF39D", "Picasso"])
                _names.append(["FFF3F1", "Chardon"])
                _names.append(["FFF46E", "Paris Daisy"])
                _names.append(["FFF4CE", "Barley White"])
                _names.append(["FFF4DD", "Egg Sour"])
                _names.append(["FFF4E0", "Sazerac"])
                _names.append(["FFF4E8", "Serenade"])
                _names.append(["FFF4F3", "Chablis"])
                _names.append(["FFF5EE", "Seashell Peach"])
                _names.append(["FFF5F3", "Sauvignon"])
                _names.append(["FFF6D4", "Milk Punch"])
                _names.append(["FFF6DF", "Varden"])
                _names.append(["FFF6F5", "Rose White"])
                _names.append(["FFF8D1", "Baja White"])
                _names.append(["FFF9E2", "Gin Fizz"])
                _names.append(["FFF9E6", "Early Dawn"])
                _names.append(["FFFACD", "Lemon Chiffon"])
                _names.append(["FFFAF4", "Bridal Heath"])
                _names.append(["FFFBDC", "Scotch Mist"])
                _names.append(["FFFBF9", "Soapstone"])
                _names.append(["FFFC99", "Witch Haze"])
                _names.append(["FFFCEA", "Buttery White"])
                _names.append(["FFFCEE", "Island Spice"])
                _names.append(["FFFDD0", "Cream"])
                _names.append(["FFFDE6", "Chilean Heath"])
                _names.append(["FFFDE8", "Travertine"])
                _names.append(["FFFDF3", "Orchid White"])
                _names.append(["FFFDF4", "Quarter Pearl Lusta"])
                _names.append(["FFFEE1", "Half and Half"])
                _names.append(["FFFEEC", "Apricot White"])
                _names.append(["FFFEF0", "Rice Cake"])
                _names.append(["FFFEF6", "Black White"])
                _names.append(["FFFEFD", "Romance"])
                _names.append(["FFFF00", "Yellow"])
                _names.append(["FFFF66", "Laser Lemon"])
                _names.append(["FFFF99", "Pale Canary"])
                _names.append(["FFFFB4", "Portafino"])
                _names.append(["FFFFF0", "Ivory"])
                _names.append(["FFFFFF", "White"])
                
                var color : String
                var rgbv : [Int]
                var hslv : [Int]
                var cnt = 0
                for var i : [String] in _names {
                    
                    color = "#" + i[0]
                    rgbv = rgb(color: color)
                    hslv = hsl(color: color)
                    i.append(String(rgbv[0]))
                    i.append(String(rgbv[1]))
                    i.append(String(rgbv[2]))
                    i.append(String(hslv[0]))
                    i.append(String(hslv[1]))
                    i.append(String(hslv[2]))
                    _names[cnt] = i
                    cnt += 1
                }
                
            }
            
            
            return _names
        }
    }

}
